'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const link=(text,url,context)=>{const a=el('a',text);if(context)a.setAttribute('aria-label',text+'：'+context);try{const u=new URL(url);if(u.protocol==='https:')a.href=u.href}catch{}return a};
function table(title,headers,rows){const wrap=el('div',undefined,'table-wrap'),t=el('table');t.append(el('caption',title));const head=el('thead'),hr=el('tr');headers.forEach(h=>{const th=el('th',h);th.scope='col';hr.append(th)});head.append(hr);t.append(head);const body=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach((v,i)=>{const td=el(i===0?'th':'td');if(i===0)td.scope='row';td.append(v instanceof Node?v:document.createTextNode(String(v??'—')));tr.append(td)});body.append(tr)});t.append(body);wrap.append(t);const focusScroll=()=>{const scrollable=wrap.scrollWidth>wrap.clientWidth;wrap.tabIndex=scrollable?0:-1;if(scrollable){wrap.setAttribute('role','region');wrap.setAttribute('aria-label',title+'，可水平捲動')}else{wrap.removeAttribute('role');wrap.removeAttribute('aria-label')}};if(typeof ResizeObserver==='function')new ResizeObserver(focusScroll).observe(wrap);else wrap.tabIndex=0;return wrap}
function head(league){const d=el('div',undefined,'league-head');d.append(el('h3',league.name),link(league.name+' 官方賽程與數據',league.source));return d}
const stat=s=>s?`${s.points} 分 · 失誤 ${s.turnovers} · 命中率 ${s.fga?((s.fgm/s.fga)*100).toFixed(1)+'%（'+s.fgm+'/'+s.fga+'）':'無出手'}`:'官方詳細統計尚未取得';
function games(l){const d=el('article',undefined,'league-block');d.append(head(l));if(l.error)d.append(el('p',l.error,'notice'));if(l.lastSuccess)d.append(el('p','來源最後成功擷取：'+l.lastSuccess,'meta'));if(l.upcoming.length)d.append(table('未來七天賽程',['臺北時間','對戰','來源'],l.upcoming.map(g=>[g.date+' '+(g.time||''),g.away+' 作客 '+g.home,link('官方賽事',g.source,g.date+' '+g.home+' vs '+g.away)])));else d.append(el('p','未來七天沒有已取得的官方賽程。','no-data'));if(l.recent.length)d.append(table('最近五場賽後統計',['日期／對戰','比分（主：客）','主要數據','來源'],l.recent.map(g=>[g.date+' '+g.home+' vs '+g.away,g.score.join('：'),g.stats?g.home+'：'+stat(g.stats.home)+'；'+g.away+'：'+stat(g.stats.away):'詳細統計尚未取得',link('官方紀錄',g.source,g.date+' '+g.home+' vs '+g.away)])));else d.append(el('p','目前沒有取得可驗證的完賽紀錄。','no-data'));return d}
function analyses(l){const d=el('article',undefined,'league-block');d.append(head(l));const reports=l.recent.slice(0,3);if(!reports.length)d.append(el('p','取得完賽紀錄後，自動生成本區分析。','no-data'));for(const g of reports){const r=el('div',undefined,'report'),h=el('div',undefined,'report-heading');h.append(el('h4',g.home+' vs '+g.away),el('span',g.score.join('：'),'score'));r.append(h,el('p',g.date,'meta'));r.append(primaryPanels(g));r.append(advancedPanel(g));r.append(link('引用：'+g.date+' '+g.home+' vs '+g.away+' 官方賽事紀錄',g.source));if(g.pbpSource)r.append(document.createTextNode(' · '),link('官方逐球資料：'+g.home+' vs '+g.away+' '+g.date,g.pbpSource));if(g.quality)r.append(el('p',g.quality,'meta'));d.append(r)}return d}
async function start(){try{const res=await fetch('data/site.json',{cache:'no-cache'});if(!res.ok)throw Error('HTTP '+res.status);const data=await res.json();document.getElementById('updated').textContent='更新嘗試：'+data.generatedAt+' · 比賽日後每日自動整理';const age=Date.now()-Date.parse(data.generatedAt);if(age>48*3600000){const n=document.getElementById('stale');n.hidden=false;n.textContent='資料已超過 48 小時未更新。請同時核對各聯盟官網。'}const gc=document.getElementById('game-content');gc.replaceChildren(...data.leagues.map(games));document.getElementById('analysis-content').replaceChildren(...data.leagues.map(analyses));const nc=document.getElementById('news-content');nc.className='news-grid';for(const n of data.news){const c=el('article',undefined,'news-card');c.append(el('h4',n.name));if(n.error)c.append(el('p',n.error,'meta'));const ul=el('ul');for(const x of n.items){const li=el('li');const newsLink=link(x.title,x.url);if(!/[\u3400-\u9fff\u3040-\u30ff]/.test(x.title))newsLink.lang='en';li.append(newsLink);if(x.date)li.append(el('p',x.date,'meta'));ul.append(li)}c.append(ul,link(n.name+' 官方賽事入口',n.source));nc.append(c)}const lc=document.getElementById('league-content');lc.className='guide-grid';for(const g of data.guides){const a=el('article',undefined,'guide');a.append(el('h3',g.name),el('p',g.description));const ul=el('ul');for(const x of g.links){const li=el('li');li.append(link(x.label,x.url));ul.append(li)}a.append(ul);if(g.teams?.length){const det=el('details');det.append(el('summary','球隊名單'),el('p',g.teams.join('、'),'meta'));a.append(det)}if(g.players?.length)a.append(el('p','近期比賽有出賽紀錄的球員（節錄）：'+g.players.join('、'),'meta'));lc.append(a)}}catch(e){document.getElementById('updated').textContent='資料讀取失敗。請透過頁尾的官方來源查看最新賽況。';document.getElementById('game-content').replaceChildren(el('p','請確認網站資料檔已發布，或稍後再試。','notice'));console.error(e)}}start();
